/**
 * Contract Type Generator
 * 
 * Reads Foundry build outputs and deployment info, then generates
 * TypeScript types for the Next.js package (similar to Scaffold-ETH 2).
 * 
 * Usage: bun run scripts/generate-contracts.ts
 */

import { readdir, readFile, writeFile, mkdir } from "fs/promises"
import { existsSync } from "fs"
import { join, resolve } from "path"

const FOUNDRY_OUT_DIR = resolve(import.meta.dir, "../out")
const DEPLOYMENTS_DIR = resolve(import.meta.dir, "../deployments")
const WEBSITE_CONTRACTS_DIR = resolve(import.meta.dir, "../../website/app/contracts")

// Contracts to include in generation (add your contract names here)
const CONTRACTS_TO_GENERATE = ["Counter"]

interface DeploymentInfo {
  chainId: number
  contracts: Record<string, { address: string }>
}

interface ContractArtifact {
  abi: readonly unknown[]
  bytecode: { object: string }
  deployedBytecode: { object: string }
}

interface GeneratedContract {
  address: string
  abi: readonly unknown[]
  inheritedFunctions?: Record<string, string>
}

type DeployedContracts = Record<number, Record<string, GeneratedContract>>

async function getContractArtifact(contractName: string): Promise<ContractArtifact | null> {
  const artifactPath = join(FOUNDRY_OUT_DIR, `${contractName}.sol`, `${contractName}.json`)
  
  if (!existsSync(artifactPath)) {
    console.warn(`⚠️  Artifact not found for ${contractName} at ${artifactPath}`)
    return null
  }
  
  const content = await readFile(artifactPath, "utf-8")
  return JSON.parse(content)
}

async function getDeployments(): Promise<DeploymentInfo[]> {
  if (!existsSync(DEPLOYMENTS_DIR)) {
    console.warn("⚠️  No deployments directory found. Run `bun deploy` first.")
    return []
  }
  
  const files = await readdir(DEPLOYMENTS_DIR)
  const deployments: DeploymentInfo[] = []
  
  for (const file of files) {
    if (file.endsWith(".json")) {
      const content = await readFile(join(DEPLOYMENTS_DIR, file), "utf-8")
      try {
        deployments.push(JSON.parse(content))
      } catch (e) {
        console.warn(`⚠️  Failed to parse ${file}`)
      }
    }
  }
  
  return deployments
}

function formatAbi(abi: readonly unknown[]): string {
  return JSON.stringify(abi, null, 2)
    .split("\n")
    .map((line, i) => (i === 0 ? line : `  ${line}`))
    .join("\n")
}

async function generateContractsFile(deployedContracts: DeployedContracts): Promise<string> {
  const chains = Object.keys(deployedContracts).map(Number).sort((a, b) => a - b)
  
  let output = `/**
 * This file is auto-generated by the contract generation script.
 * Do not edit manually. Run \`bun generate\` to regenerate.
 * 
 * @generated
 */

import type { GenericContractsDeclaration } from "./contractTypes"

const deployedContracts = {\n`

  for (const chainId of chains) {
    const contracts = deployedContracts[chainId]
    output += `  ${chainId}: {\n`
    
    for (const [name, contract] of Object.entries(contracts)) {
      output += `    ${name}: {\n`
      output += `      address: "${contract.address}" as const,\n`
      output += `      abi: ${formatAbi(contract.abi)} as const,\n`
      if (contract.inheritedFunctions) {
        output += `      inheritedFunctions: ${JSON.stringify(contract.inheritedFunctions, null, 2)},\n`
      }
      output += `    },\n`
    }
    
    output += `  },\n`
  }

  output += `} as const satisfies GenericContractsDeclaration

export default deployedContracts
`

  return output
}

async function generateContractTypesFile(): Promise<string> {
  return `/**
 * Contract type definitions for type-safe contract interactions.
 * This file provides the base types used by deployedContracts.ts
 * 
 * @generated
 */

import type { Abi, Address } from "viem"

export type InheritedFunctions = Record<string, string>

export type GenericContract = {
  address: Address
  abi: Abi
  inheritedFunctions?: InheritedFunctions
}

export type GenericContractsDeclaration = Record<
  number,
  Record<string, GenericContract>
>

/**
 * Utility type to extract contract names from deployed contracts
 */
export type ContractName<TContracts extends GenericContractsDeclaration> = {
  [ChainId in keyof TContracts]: keyof TContracts[ChainId]
}[keyof TContracts]

/**
 * Utility type to get a specific contract's type
 */
export type Contract<
  TContracts extends GenericContractsDeclaration,
  TName extends ContractName<TContracts>,
  TChainId extends keyof TContracts = keyof TContracts
> = TContracts[TChainId][TName]
`
}

async function generateIndexFile(): Promise<string> {
  return `/**
 * Contracts barrel export
 * @generated
 */

export { default as deployedContracts } from "./deployedContracts"
export * from "./contractTypes"
`
}

async function main() {
  console.log("🔧 Generating contract types...\n")

  // Ensure output directory exists
  if (!existsSync(WEBSITE_CONTRACTS_DIR)) {
    await mkdir(WEBSITE_CONTRACTS_DIR, { recursive: true })
    console.log(`📁 Created ${WEBSITE_CONTRACTS_DIR}`)
  }

  // Get deployments
  const deployments = await getDeployments()
  
  if (deployments.length === 0) {
    console.log("ℹ️  No deployments found. Generating with placeholder addresses...")
    // Generate with zero address as placeholder for development
  }

  // Build deployed contracts object
  const deployedContracts: DeployedContracts = {}

  // Process each deployment
  for (const deployment of deployments) {
    const chainId = deployment.chainId
    deployedContracts[chainId] = {}

    for (const contractName of CONTRACTS_TO_GENERATE) {
      const contractDeployment = deployment.contracts[contractName]
      if (!contractDeployment) {
        console.warn(`⚠️  ${contractName} not found in deployment for chain ${chainId}`)
        continue
      }

      const artifact = await getContractArtifact(contractName)
      if (!artifact) continue

      deployedContracts[chainId][contractName] = {
        address: contractDeployment.address,
        abi: artifact.abi,
      }

      console.log(`✅ ${contractName} on chain ${chainId}: ${contractDeployment.address}`)
    }
  }

  // If no deployments, generate with local chain placeholder
  if (Object.keys(deployedContracts).length === 0) {
    const localChainId = 31337 // Anvil default
    deployedContracts[localChainId] = {}

    for (const contractName of CONTRACTS_TO_GENERATE) {
      const artifact = await getContractArtifact(contractName)
      if (!artifact) continue

      deployedContracts[localChainId][contractName] = {
        address: "0x0000000000000000000000000000000000000000",
        abi: artifact.abi,
      }

      console.log(`📝 ${contractName} (placeholder - run deploy to get real address)`)
    }
  }

  // Generate files
  const contractsContent = await generateContractsFile(deployedContracts)
  const typesContent = await generateContractTypesFile()
  const indexContent = await generateIndexFile()

  await writeFile(join(WEBSITE_CONTRACTS_DIR, "deployedContracts.ts"), contractsContent)
  await writeFile(join(WEBSITE_CONTRACTS_DIR, "contractTypes.ts"), typesContent)
  await writeFile(join(WEBSITE_CONTRACTS_DIR, "index.ts"), indexContent)

  console.log(`
📦 Generated files:
   - ${WEBSITE_CONTRACTS_DIR}/deployedContracts.ts
   - ${WEBSITE_CONTRACTS_DIR}/contractTypes.ts
   - ${WEBSITE_CONTRACTS_DIR}/index.ts

✨ Done! Contract types are ready to use.
`)
}

main().catch((error) => {
  console.error("❌ Generation failed:", error)
  process.exit(1)
})
