/**
 * This file is auto-generated by the contract generation script.
 * Do not edit manually. Run `bun generate` to regenerate.
 * 
 * @generated
 */

import type { GenericContractsDeclaration } from "./contractTypes"

const deployedContracts = {
  31337: {
    Counter: {
      address: "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512" as const,
      abi: [
    {
      "type": "function",
      "name": "increment",
      "inputs": [],
      "outputs": [],
      "stateMutability": "nonpayable"
    },
    {
      "type": "function",
      "name": "number",
      "inputs": [],
      "outputs": [
        {
          "name": "",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "stateMutability": "view"
    },
    {
      "type": "function",
      "name": "setNumber",
      "inputs": [
        {
          "name": "newNumber",
          "type": "uint256",
          "internalType": "uint256"
        }
      ],
      "outputs": [],
      "stateMutability": "nonpayable"
    }
  ] as const,
    },
  },
} as const satisfies GenericContractsDeclaration

export default deployedContracts
